"""Step 17 — assemble every number the manuscript may cite, with provenance.

Writes paper/FACTS.md. The rule for the manuscript is that no number appears
unless it can be traced to a file listed here.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src"))

import pandas as pd  # noqa: E402

from mcpstudy import config  # noqa: E402

OUT = os.path.join(config.PROJECT_ROOT, "paper")

SECTIONS = [
    ("RQ3 / RQ4 — population", "results/tables/t01_census_overview.csv"),
    ("RQ4 — manifest field completeness", "results/tables/t02_field_completeness.csv"),
    ("RQ3 — transports", "results/tables/t04_transports.csv"),
    ("RQ3 — package registries", "results/tables/t05_package_registries.csv"),
    ("RQ3 — schema adoption", "results/tables/t06_schema_adoption.csv"),
    ("RQ3 — publishing timeline", "results/tables/t07_publishing_timeline.csv"),
    ("RQ3 — staleness", "results/tables/t16_staleness.csv"),
    ("RQ3 — version churn concentration", "results/tables/t20_version_churn_concentration.csv"),
    ("RQ2 — credential hygiene", "results/tables/t11_credential_hygiene.csv"),
    ("RQ2 — most common env vars", "results/tables/t12_most_common_env_vars.csv"),
    ("RQ2 — remote endpoint hygiene", "results/tables/t13_remote_endpoint_hygiene.csv"),
    ("RQ1 — tool interface summary", "results/tables/t21_tool_interface_summary.csv"),
    ("RQ1 — tool extraction coverage", "results/tables/t23_tool_extraction_coverage.csv"),
    ("RQ1 — naming conventions", "results/tables/t10_naming_conventions.csv"),
    ("RQ1 — description issues", "results/tables/t09_description_issues.csv"),
    ("RQ1 — description length", "results/tables/t09b_description_stats.csv"),
    ("RQ3 — package profile", "results/tables/t24_package_profile.csv"),
    ("RQ3 — licence distribution", "results/tables/t25_licence_distribution.csv"),
    ("RQ3 — repository profile", "results/tables/t26_repository_profile.csv"),
    ("RQ3 — repositories by language", "results/tables/t27_repositories_by_language.csv"),
    ("RQ3 — manifest properties vs activity", "results/tables/t28_manifest_properties_vs_activity.csv"),
    ("T1 — registry versions vs GitHub releases", "results/tables/t29_registry_versions_vs_github_releases.csv"),
    ("T1 — release signal agreement", "results/tables/t30_release_signal_agreement.csv"),
    ("Uncertainty — bootstrap intervals", "results/tables/t31_bootstrap_intervals.csv"),
    ("RQ4 — human validation of extraction", "results/validation/part_a_summary.csv"),
    ("RQ4 — extraction miss reasons", "results/validation/part_a_miss_reasons.csv"),
    ("RQ2 — human-coded security summary", "results/validation/part_b_summary.csv"),
    ("RQ2 — human-coded security distributions", "results/validation/part_b_crosstabs.csv"),
    ("RQ2 — security by transport", "results/validation/part_b_by_transport.csv"),
    ("RQ1 — human-coded description quality", "results/validation/part_c_summary.csv"),
    ("RQ1 — description quality by language", "results/validation/part_c_by_language.csv"),
    ("Inter-rater reliability", "results/validation/interrater_summary.csv"),
    ("T1 — narrative note", "results/validation/t1_note.md"),
]


def main():
    os.makedirs(OUT, exist_ok=True)
    lines = ["# Fact sheet\n",
             "Every number the manuscript may cite, with the file it came from.\n",
             "Regenerated by `scripts/17_build_facts.py`.\n"]
    for title, rel in SECTIONS:
        path = os.path.join(config.PROJECT_ROOT, rel)
        lines.append("\n---\n\n## %s\n\n`%s`\n" % (title, rel))
        if not os.path.isfile(path):
            lines.append("\n_(missing)_\n")
            continue
        if path.endswith(".md"):
            with open(path, encoding="utf-8") as fh:
                lines.append("\n" + fh.read() + "\n")
            continue
        frame = pd.read_csv(path)
        if len(frame) > 40:
            frame = frame.head(40)
            lines.append("\n_(first 40 rows)_\n")
        lines.append("\n```\n%s\n```\n" % frame.to_string(index=False))

    path = os.path.join(OUT, "FACTS.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("wrote %s (%d bytes, %d sections)"
          % (path, os.path.getsize(path), len(SECTIONS)))


if __name__ == "__main__":
    main()
